name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - run: ./gradlew check build publishToMavenLocal --stacktrace --parallel --warning-mode=fail
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: ./*/build/libs/
      - uses: actions/upload-artifact@v3
        with:
          name: Maven Local
          path: /root/.m2/repository
